### ISSUE TITLE
Custom slash commands taking precedence over built-in ones

### ISSUE THREAD

**Issue by allejo** [BZFlag-Dev/bzflag-import-3#17]
It seems that custom slash commands took precedence over built-in ones in 2.99 so could this be back ported to be the case for 2.4.x as it wouldn't break the protocol?

As an example as to why this could be useful, a plug-in could hide the identity of a hidden admin when they take certain actions such as muting, kicking, or banning a player without the need for modifying BZFS. Eventually these features could be implemented into BZFS but to start off, it could be tested via a plug-in.

Another example would be disabling a slash command from being used, like my League Overseer plug-in could overload the /countdown or /gameover commands to send the players a custom message as to why the command as been disabled instead of giving them both a message through the bz_eSlashCommandEvent and then permission denied message right after. This would also prevent the command from being used should the server owner accidentally forget to remove the permission from the group permissions file.

If SlashCommand() returns false, then bzfs will proceed with handling it, otherwise the plugin will handle it.

**Comment by JMakey** [comment]
If plugins can't override built-in slash commands, then motivated server owners will modify bzfs itself to make it work the way they want.  We might as well allow plugins to override them.

**Comment by macsforme** [comment]
It looks like this behavior will be useful. I'm all for it.
